# Generated by Django 5.1.3 on 2025-11-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="anno",
            field=models.IntegerField(),
        ),
    ]
