# Generated by Django 5.1.3 on 2025-11-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_anno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="anno",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
