# Generated by Django 5.1.3 on 2025-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_passwordhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailedLoginIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.CharField(max_length=45, unique=True)),
                ("attempts", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "failed_login_ips",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
