# Generated by Django 5.1.3 on 2025-11-12 22:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('authors', models.TextField(verbose_name='Autores')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('journal', models.CharField(max_length=300, verbose_name='Revista')),
                ('volume', models.CharField(blank=True, max_length=50, null=True, verbose_name='Volumen')),
                ('pages', models.CharField(blank=True, max_length=50, null=True, verbose_name='Páginas')),
                ('doi', models.CharField(blank=True, max_length=200, null=True, verbose_name='DOI')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('file', models.FileField(blank=True, null=True, upload_to='publications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo')),
                ('nivel', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], max_length=1, verbose_name='Nivel')),
                ('status', models.CharField(choices=[('en_proceso', 'En Proceso'), ('pending', 'Pendiente de Revisión'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('review_comments', models.TextField(blank=True, null=True, verbose_name='Comentarios de Revisión')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'jefe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(blank=True, limit_choices_to={'role': 'tutor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications_as_tutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'publications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(verbose_name='Opinión')),
                ('recommendation', models.CharField(choices=[('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('revision', 'Requiere Revisión')], max_length=20, verbose_name='Recomendación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Opinión')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_opinions', to='publications.publication')),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opinión de Tutor',
                'verbose_name_plural': 'Opiniones de Tutores',
                'db_table': 'tutor_opinions',
                'ordering': ['-created_at'],
                'unique_together': {('publication', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='TutorStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('progress', models.IntegerField(default=0, verbose_name='Progreso (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutors_assigned', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(limit_choices_to={'role': 'tutor'}, on_delete=django.db.models.deletion.CASCADE, related_name='students_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Tutor-Estudiante',
                'verbose_name_plural': 'Relaciones Tutor-Estudiante',
                'db_table': 'tutor_students',
                'unique_together': {('tutor', 'student')},
            },
        ),
    ]
