# Generated by Django 5.1.3 on 2025-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Revista'),
        ),
    ]
