# Generated by Django 5.1.3 on 2025-11-19 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_alter_publication_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="publications/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "doc", "docx"]
                    )
                ],
                verbose_name="Archivo",
            ),
        ),
    ]
