# Generated by Django 5.1.3 on 2026-01-21 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_alter_publication_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="opinions/%Y/%m/", verbose_name="Archivo de Opinión"
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="URL del Archivo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Opinión"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "estudiante"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        limit_choices_to={"role": "tutor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_opinions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinión sobre Estudiante",
                "verbose_name_plural": "Opiniones sobre Estudiantes",
                "db_table": "student_opinions",
                "ordering": ["-created_at"],
                "unique_together": {("tutor", "student")},
            },
        ),
    ]
