# Generated by Django 5.1.3 on 2025-12-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Crear"),
                    ("update", "Actualizar"),
                    ("delete", "Eliminar"),
                    ("login", "Inicio de Sesión"),
                    ("logout", "Cierre de Sesión"),
                    ("review", "Revisión"),
                    ("approve", "Aprobación"),
                    ("reject", "Rechazo"),
                    ("user_lock", "Bloqueo de Usuario"),
                    ("ip_block", "Bloqueo de IP"),
                    ("ip_blocked_attempt", "Intento desde IP Bloqueada"),
                    ("admin_unlock", "Desbloqueo por Admin"),
                    ("admin_ip_deny", "Acceso Admin Denegado por IP"),
                ],
                max_length=20,
                verbose_name="Acción",
            ),
        ),
    ]
