# Generated by Django 5.1.3 on 2025-12-01 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0004_alter_systemlog_action_maxlength"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Session Key"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actividad"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión Activa",
                "verbose_name_plural": "Sesiones Activas",
                "db_table": "active_sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("failed_login", "Intento Fallido de Login"),
                            ("simultaneous_access", "Acceso Simultáneo"),
                            ("system_error", "Error del Sistema"),
                            ("db_error", "Error de Base de Datos"),
                            ("unauthorized_attempt", "Operación No Autorizada"),
                            (
                                "post_approval_modification",
                                "Modificación Post-Aprobación",
                            ),
                            ("user_locked", "Usuario Bloqueado"),
                            ("ip_blocked", "IP Bloqueada"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("critical", "Crítico"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Severidad",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("message", models.TextField(verbose_name="Mensaje")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Metadatos"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Leída")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Resuelta"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Leída en"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resuelta en"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creada"),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación de Admin",
                "verbose_name_plural": "Notificaciones de Admin",
                "db_table": "admin_notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
